// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sarauvembzbneunhssud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhcmF1dmVtYnpibmV1bmhzc3VkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkyMTc4MjEsImV4cCI6MjA4NDc5MzgyMX0.H1ww5qaVw2WGX7N9Ls6eM2q5_se8cj_J6hsw12XeNpM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});